### ISSUE TITLE
Explorer preview "word could not create the work file"

### ISSUE THREAD

**Issue by felivix** [MicrosoftDocs/OfficeDocs-Support#219]
Creating the folder labeled INetCacheContent.Word did NOT resolve the issue. 

In the File Explorer every time I click on a Word document to look at the preview the error message "Word could not create the work file. Check the Temp environment variable." pops up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f069189a-7af4-d6df-1509-f30af7d3c01d
* Version Independent ID: df260ca7-16dd-d2f8-1de3-91e0b71f67d4
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file#feedback)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the-work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by br14nm4** [comment]
I am having the exact same issue. I have tried all the registry changes suggested online but everything looks correct. %Userprofile% is being used for all instances. I was able to resolve this error by uninstalling 64bit and installing 32bit. 
I then ran into the same error with .msg files for Outlook. 
![image](https://user-images.githubusercontent.com/36397434/69381349-7ad48600-0d04-11ea-89a8-7d7be284b908.png)

**Comment by br14nm4** [comment]
Here is the error for word docs when i have 64bit installed. 
(Note that if i acknowledge the error the preview does load.) 
![image](https://user-images.githubusercontent.com/36397434/69381403-9e97cc00-0d04-11ea-8085-a7ec103f21dd.png)

**Comment by ben71fl** [comment]
Having the issue as well, 10 brand new computers, Win10 1903 / Office 2019 32bit Pro Plus (VLM). I can click Okay twice and the message goes away and preview shows up. No office files preview Word/Excel that I have tested. Local/MyDocs/Network Shares. Updated to 1909, nothing changed, turned off UAC, opened explorer as administrator. etc etc.

**Comment by br14nm4** [comment]
Still no update on this? Looks like i'm going to have to just re-image the machine.... LAME!

**Comment by rdhainaut** [comment]
I have encountered this issue On Windows 10 with Microsoft Office 64 bits (with Word and Outlook).

This is my solution to fix the issue in cmd 
Type "regedit"
   Go to:
   1. HKEY_CURRENT_USER
   2. Software
   3. Microsoft
   4. Windows
   5. Current Version
   6. Explorer
   7. User Shell Folders
=> Replace the "Cache" data with this: %USERPROFILE%\\AppData\\Local\\Microsoft\\Windows\\INetCache

My organisation has changed this cache setting by
%USERPROFILE%\AppData\Local\Microsoft\Windows\Temporary Internet Files but it causes an error on my machine ... 
Their workaround solution was to install 32 bits version but it s an unsatisfying solution because it s regression so i have found this better solution.

Et voilà :)

**Comment by donderwink1** [comment]
I had the exact same issue, and tried all solutions with no avail. Eventually, I found it was the 32-bit version of office that was evil. Installing 64 bit office solved the issue.

**Comment by alxdean** [comment]
The Folder in question exists. The Registry Setting is as expected. This Problem started after I uninstalled the 32 bit version and installed the 64bit version of Office 365... so even donderwin1's solution won't work for me :-(

**Comment by Uberck** [comment]
Any news on this? Issue is still occurring with Word 2019. The preview does load, but not before the annoying popup shows up once or twice. Any updates with this annoying bug. This seems to only happen with Word-document previews in the preview pane. Again, this is Word 2019 as part of the 2019 Pro-Plus suite.

**Comment by Uberck** [comment]
![img](https://user-images.githubusercontent.com/12820409/74124877-c5e29480-4ba1-11ea-82d8-2ace66e399ff.JPG)
How do you install the 64 bit version of Office. Didn't see an option during install...

**Comment by donderwink1** [comment]
If you download it from office 365 it's under install office > other install options > install 32 / 64 bit office. https://support.office.com/en-us/article/download-and-install-or-reinstall-office-365-or-office-2019-on-a-pc-or-mac-4414eaaf-0478-48be-9c42-23adc4716658

**Comment by docfour** [comment]
I had this issue occuring with a fresh windows 10 installation and Word 2010. In the meanwhile, I updated to Word 2019 Home and it is still occuring. 

None of the solutions seems to work and the creation of the above folder is misleading as normally, User Shell Folder points to %USERPROFILE%\AppData\Local\Microsoft\Windows\INetCache and inside that folder is a hidden Content.Word folder where Word creates its tmp files.

I monitored word startup with procmon and it tries to create 3 tmp files inside this folder with R/W permissions, the first creation fails resulting in the error message with "could not create work file check tmp environment variable and also in opening the word file write protected.
I checked folder permissions and they are correct (full access to user account).

There are a lot of "solutions" outside, some say set User Shell Folder to INetCache, others to Temporary Internet Files, ... 

It would be nice, if Microsoft could provide us with a solution or a strategy to pin down the cause of his annoying problem.

**Comment by YoshiNoodles** [comment]
I've been having this problem now with my Asus tablet running Windows RT.  It started with Word having issues opening some documents off of a flash drive, and now it gives me this error every time I go to open Word in the first place.  This is, I don't get it with Excel or PowerPoint.  And using the RegEdit doesn't do anything.  Any help would be appreciated.

**Comment by johnboden** [comment]
I have an answer to the problem and one which is linked to Microsoft store issues.

- In Windows 10 go to settings cog in the start menu
- Next go to updates and security
- Next go troubleshooting
- Go the bottom on the right-hand window and select Windows Store Apps
- Run the troubleshooting you should find it identifies a problem with the windows temp (moved)
- Complete the fix and look for the tick next to the windows temp file issue (ignore other issues)
- Close the troubleshooting and other programs and reboot
- When you reboot wait 5 mins as other applications may start updates (due to the issue)
- When finished start Microsoft Word and the problem should be resolved

BTW other reg edit fixes and temp file environment fixes did not work for me however, this did.

**Comment by TechDavid** [comment]
A customer has the same issue with the prewiev of word documents.
Accepting the error message twice let's the prewiev open.
Office is running as 32-Bit.

All the comments above did not resolve the issue.

Please provide a solution to this issue.

**Comment by contoso-eu** [comment]
Solved! - I had the same problems with previews in Word and Excel. The solutions above did'nt work for me. But i could solve this problem for me with deleting the following registry keys (no reboot was needed). 

Word Preview : HKCR\CLSID\{84F66100-FF7C-4fb4-B0C0-02CD7FB668FE}
PowerPoint Preview : HKCR\CLSID\{65235197-874B-4A07-BDC5-E65EA825B718}
Excel Preview : HKCR\CLSID\{00020827-0000-0000-C000-000000000046}

**Comment by mswinden** [comment]
contoso-eu, this absolutely worked for me. I have tried every solution in this thread; to no avail. But this sir, worked for me. I would like  to add a few observations however.
 
Below is the EXACT process I used and it worked flawlessly. Keep in mind that Word is where I had my issues so I chose the "Word" option from "contoso-eu" post.
1) Delete registry key : HKCR\CLSID{84F66100-FF7C-4fb4-B0C0-02CD7FB668FE}
2) Launch Task Manager and kill (end) all instances of Word (processes).
3) Wait a couple of minutes...literally.
4) Launch Word (not a Word file). Simply open Word.
5) Close Word 
6) Verify it worked by launching Word from ".docx / .doc" file.
7) Success!

Further, I also notice that Word seems to launch/open faster now. 

I am running Office 365 (SaaS) - stays updated
Win 10 
64 bit
Laptop - Lenovo (Legion)

Hope this helps everyone out there! and Thanks again to contoso-eu!

**Comment by contoso-eu** [comment]
I'm happy that I could help you @mswinden

**Comment by contoso-eu** [comment]
I'm happy that I could help you @mswinden

**Comment by felivix** [comment]
@contoso-eu / @mswinden 
Thank you. Your clear instructions resolved the problem. Much appreciated.
Besten Dank. Ihre Anweisung hat hervorragend geklappt. Ich schätze Ihr Unterstützung.

**Comment by mvpromise** [comment]
> ![img](https://user-images.githubusercontent.com/12820409/74124877-c5e29480-4ba1-11ea-82d8-2ace66e399ff.JPG)
> How do you install the 64 bit version of Office. Didn't see an option during install...

use the ODT method and select 64bit 
you can use the  link:https://docs.microsoft.com/en-us/deployoffice/office2019/deploy

**Comment by Ab-Abdurrahman** [comment]
Resolution
To resolve this issue, create a new folder on your computer.

1.Start Windows Explorer

2.Locate the folder location C:\Users\userprofile\AppData\Local\Microsoft\Windows

3.Create the folder labeled INetCacheContent.Word.

I got the solution from [Microsoft support website](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file#:~:text=When%20you%20save%20a%20document%20in%20Microsoft%20Word%2C%20you%20receive,to%20create%20new%20temporary%20files.)
